#!/bin/bash
export GOOS=linux
export GOARCH=arm
export GOARM=5
echo "compiling $1 ..."
/home/j/Work/go4arm/bin/go build $1.go
echo "moving target to /tftpboot ..."
mv $1 ..
ls -l /tftpboot 
echo "done!"
ls -l .

