#!/bin/bash
export GOOS=linux
export GOARCH=arm
export GOARM=5
export GOPATH=/tftpboot/project4
export GOBIN=/tftpboot/project4/bin
alias go="/home/j/Work/go4arm/bin/go"
alias l="ls --color"
alias ll="ls -l"
